version: '2'
services:
    easyconnect:
        image: hagb/docker-easyconnect:7.6.7 # latest, vncless, 7.6.3, vncless-7.6.3, 7.6.7, vncless-7.6.7
        devices:
          - /dev/net/tun
        cap_add: 
          - NET_ADMIN
        volumes:
          - $HOME/.ecdata:/root
        environment:
          - URLWIN=1
          - PASSWORD=xxxx
          # VNC 性能优化配置
          - VNC_SIZE=1024x768          # 使用标准分辨率避免屏幕创建问题
          - VNC_NETWORK_MODE=balanced  # fast/balanced/slow
          - VNC_ENCODING=tight         # tight/zrle/hextile/raw
          - VNC_QUALITY=6              # 0-9 (0=最高压缩, 9=最高质量)
          - VNC_COMPRESS=6             # 0-9 (0=无压缩, 9=最高压缩)
          - VNC_FRAMERATE=30           # 1-60 fps
          - VNC_DEPTH=24               # 8/16/24/32 bit
          - VNC_AUTO_OPTIMIZE=1        # 启用自动优化
          - VNC_AUTO_LOWRES=1          # 启用低资源自动检测
          - VNC_MONITOR_INTERVAL=30    # 性能监控间隔(秒)
        ports:
          - "127.0.0.1:5901:5901"
          - "127.0.0.1:1080:1080"
          - "127.0.0.1:8888:8888"
