#!/bin/bash
# VNC 性能优化使用示例

echo "=== VNC 性能优化功能演示 ==="

echo ""
echo "1. 高速网络环境 (LAN):"
echo "docker run --rm --device /dev/net/tun --cap-add NET_ADMIN -ti \\"
echo "  -e PASSWORD=your_password \\"
echo "  -e VNC_NETWORK_MODE=fast \\"
echo "  -e VNC_ENCODING=raw \\"
echo "  -e VNC_QUALITY=9 \\"
echo "  -e VNC_FRAMERATE=60 \\"
echo "  -e VNC_DEPTH=32 \\"
echo "  -p 127.0.0.1:5901:5901 \\"
echo "  -p 127.0.0.1:1080:1080 \\"
echo "  -p 127.0.0.1:8888:8888 \\"
echo "  hagb/docker-easyconnect:latest"

echo ""
echo "2. 低速网络环境 (WAN/Mobile):"
echo "docker run --rm --device /dev/net/tun --cap-add NET_ADMIN -ti \\"
echo "  -e PASSWORD=your_password \\"
echo "  -e VNC_NETWORK_MODE=slow \\"
echo "  -e VNC_ENCODING=tight \\"
echo "  -e VNC_QUALITY=2 \\"
echo "  -e VNC_COMPRESS=9 \\"
echo "  -e VNC_FRAMERATE=15 \\"
echo "  -e VNC_DEPTH=16 \\"
echo "  -p 127.0.0.1:5901:5901 \\"
echo "  -p 127.0.0.1:1080:1080 \\"
echo "  -p 127.0.0.1:8888:8888 \\"
echo "  hagb/docker-easyconnect:latest"

echo ""
echo "3. 自动优化模式:"
echo "docker run --rm --device /dev/net/tun --cap-add NET_ADMIN -ti \\"
echo "  -e PASSWORD=your_password \\"
echo "  -e VNC_AUTO_OPTIMIZE=1 \\"
echo "  -e VNC_MONITOR_INTERVAL=30 \\"
echo "  -p 127.0.0.1:5901:5901 \\"
echo "  -p 127.0.0.1:1080:1080 \\"
echo "  -p 127.0.0.1:8888:8888 \\"
echo "  hagb/docker-easyconnect:latest"

echo ""
echo "4. 容器运行后的性能监控和优化命令:"
echo ""
echo "# 查看 VNC 性能状态"
echo "docker exec <container_name> vnc-performance-monitor.sh status"
echo ""
echo "# 启动性能监控"
echo "docker exec <container_name> vnc-performance-monitor.sh monitor &"
echo ""
echo "# 自动优化配置"
echo "docker exec <container_name> vnc-optimize.sh auto"
echo ""
echo "# 应用优化配置"
echo "docker exec <container_name> vnc-optimize.sh apply"
echo ""
echo "# 运行性能测试"
echo "docker exec <container_name> vnc-optimize.sh test"

echo ""
echo "=== 环境变量说明 ==="
echo "VNC_NETWORK_MODE: 网络模式 (fast/balanced/slow)"
echo "VNC_ENCODING:     编码格式 (tight/zrle/hextile/raw)"
echo "VNC_QUALITY:      JPEG质量 (0-9, 0=最高压缩, 9=最高质量)"
echo "VNC_COMPRESS:     压缩级别 (0-9, 0=无压缩, 9=最高压缩)"
echo "VNC_FRAMERATE:    帧率限制 (1-60 fps)"
echo "VNC_DEPTH:        色彩深度 (8/16/24/32 bit)"
echo "VNC_DEFERTIME:    延迟更新时间 (0-200 ms)"
echo "VNC_AUTO_OPTIMIZE: 启用自动优化 (0/1)"
echo "VNC_MONITOR_INTERVAL: 监控间隔 (秒)"

echo ""
echo "=== 性能调优建议 ==="
echo "高性能场景 (LAN):"
echo "  - 使用 raw 或 zrle 编码"
echo "  - 设置高质量 (8-9)"
echo "  - 低压缩 (0-2)"
echo "  - 高帧率 (60fps)"
echo "  - 高色彩深度 (32bit)"
echo ""
echo "低带宽场景 (WAN/Mobile):"
echo "  - 使用 tight 编码"
echo "  - 设置低质量 (1-3)"
echo "  - 高压缩 (7-9)"
echo "  - 低帧率 (10-20fps)"
echo "  - 低色彩深度 (16bit)"
echo ""
echo "平衡场景:"
echo "  - 使用 tight 编码"
echo "  - 中等质量 (5-7)"
echo "  - 中等压缩 (5-7)"
echo "  - 中等帧率 (25-35fps)"
echo "  - 标准色彩深度 (24bit)"
